/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 78
#define YY_END_OF_BUFFER 79
static yyconst short int yy_accept[209] =
    {   0,
        0,    0,    0,    0,   79,   77,   52,    1,   63,   44,
       77,   58,   59,   77,   14,   15,   55,   53,   18,   54,
       56,   49,   19,   72,   57,   71,   50,   12,   13,   60,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   16,   77,   17,    9,   11,    8,   10,
       52,   76,   44,   43,    0,    0,   68,   69,    0,    0,
        0,   66,   61,   64,   62,   65,    5,    4,   67,    0,
       49,    0,   74,   75,   73,   50,   51,   50,   50,   50,
       50,   50,   50,   25,   50,   50,   50,   50,   27,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   70,

        9,    8,    7,    6,    0,    0,    0,   45,    0,    0,
        0,   45,    4,   48,   47,   50,   50,   50,   50,   50,
       50,   50,   50,   26,   50,   28,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   50,    0,    0,   46,    0,
        0,   45,   50,   41,   20,   50,   50,   50,   22,   50,
       39,   29,   50,   50,   50,   50,   50,   50,   50,   36,
       50,    0,    0,   37,   50,   50,   50,   23,   50,   31,
       50,   50,   50,   50,   50,   24,    0,    0,   50,   50,
       21,   30,   32,   33,   34,   40,   50,    0,    0,   50,
       42,   50,    0,    0,   38,   35,    0,    0,    0,    3,

        3,    3,    0,    0,    0,    0,    2,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   20,
       20,   20,   20,   20,   20,   20,   20,    1,   21,   22,
       23,   24,    1,    1,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,   29,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   25,   40,   41,   25,   42,
       43,   25,   25,   44,   45,   46,   47,   48,   49,   25,
       25,   50,   51,   52,   53,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    4,    1,    1,    1,    5,    4,    5,    5,
        1,    1,    1,    1,    6,    7,    1,    1,    1,    8,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        1,    1,    1
    } ;

static yyconst short int yy_base[222] =
    {   0,
        0,    0,   51,   52,  500,  620,   54,  620,  476,  492,
       23,  474,  487,   49,  620,  620,  472,   49,  620,   44,
       48,   58,  620,  471,  470,  469,   53,  620,  620,  620,
       54,   56,   62,   55,   65,   74,   77,   84,   85,   86,
       92,  100,  103,  620,  439,  620,    0,  620,   55,  426,
      119,  620,  427,  620,  390,  352,  620,  620,  368,  363,
      141,  620,  620,  620,  620,  620,  620,    0,  620,   70,
      119,   82,  620,  620,  620,  116,  620,  119,  122,  129,
      132,  139,  140,  141,  149,  152,  154,  160,  166,  167,
      173,  174,  175,  182,  181,  184,  191,  196,  198,  620,

        0,  143,  620,  620,  326,  317,  330,  620,  325,  324,
      322,  317,    0,  210,  214,  212,  214,  220,  201,  222,
      225,  228,  230,  236,  239,  241,  242,  244,  250,  247,
      255,  257,  262,  267,  269,  270,  268,  245,  620,  274,
      268,  620,  272,  275,  283,  284,  289,  290,  291,  292,
      298,  299,  300,  307,  313,  315,  316,  321,  326,  329,
      331,  233,  192,  334,  339,  341,  342,  344,  349,  350,
      358,  357,  359,  360,  369,  370,  181,  168,  371,  376,
      377,  378,  383,  384,  386,  389,  391,  160,  118,  394,
      397,  402,  146,  187,  404,  405,  436,  237,    0,  486,

      136,    0,  120,   93,  111,   85,  620,  620,  536,  544,
      552,  555,  563,  571,  579,  587,  595,  603,  609,   68,
      613
    } ;

static yyconst short int yy_def[222] =
    {   0,
      208,    1,  209,  209,  208,  208,  208,  208,  208,  210,
      208,  208,  208,  211,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  212,  208,  208,  208,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  208,  208,  208,  213,  208,  208,  208,
      208,  208,  210,  208,  208,  208,  208,  208,  214,  208,
      215,  208,  208,  208,  208,  208,  208,  216,  208,  208,
      208,  208,  208,  208,  208,  212,  208,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  208,

      213,  208,  208,  208,  208,  208,  214,  208,  217,  218,
      214,  208,  216,  208,  208,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  208,  208,  208,  217,
      218,  208,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  208,  208,  212,  212,  212,  212,  212,  212,  212,
      212,  212,  212,  212,  212,  212,  208,  208,  212,  212,
      212,  212,  212,  212,  212,  212,  212,  208,  208,  212,
      212,  212,  219,  208,  212,  212,  208,  208,  220,  197,

      200,  197,  221,  208,  221,  208,  208,    0,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208
    } ;

static yyconst short int yy_nxt[674] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,   14,
       15,   16,   17,   18,   19,   20,    6,   21,   22,   22,
       23,   24,   25,   26,   27,   28,    6,   29,   30,   27,
       27,   31,   32,   33,   34,   35,   36,   27,   37,   27,
       38,   27,   27,   39,   40,   27,   41,   42,   43,   27,
       44,   45,   46,   48,   48,   51,   55,   51,   60,   65,
       67,   56,   63,   49,   49,   68,   66,  102,   50,   50,
       69,   64,  103,  203,   70,   61,   71,   71,   77,   77,
       77,   77,   78,   78,   78,   78,   80,   77,  114,  114,
       77,   78,   72,   81,   78,   85,   83,   79,   82,   77,

      115,  115,   77,   78,   84,   86,   78,   87,  207,   77,
       77,   77,   89,   78,   78,   78,   88,   77,   90,   92,
       51,   78,   51,   93,   94,   77,   91,  204,   77,   78,
      206,   95,   78,   97,   96,   70,  204,   71,   71,  201,
       99,   77,   98,  110,   77,   78,  111,   77,   78,  193,
      112,   78,  194,   72,   77,  102,  116,   77,   78,  111,
      103,   78,  118,  193,   77,   77,   77,  111,   78,   78,
       78,  111,  111,  117,   77,  120,  111,   77,   78,   77,
      119,   78,  111,   78,  111,   77,  111,  121,  111,   78,
      198,   77,   77,  122,  123,   78,   78,  124,   77,   77,

       77,  189,   78,   78,   78,  125,   77,   77,  199,   77,
       78,   78,  126,   78,  127,  188,   77,  129,  130,  128,
       78,   77,  133,   77,  132,   78,   77,   78,  114,  114,
       78,  131,  115,  115,  135,  134,  136,   77,  178,   77,
      198,   78,  143,   78,   72,   77,  146,   77,  144,   78,
       77,   78,  147,   77,   78,   77,  148,   78,  199,   78,
      150,   77,  149,  145,   77,   78,   77,   77,   78,   77,
       78,   78,   77,   78,  177,   77,   78,  139,  152,   78,
       77,  151,   77,  139,   78,  163,   78,   77,  155,  156,
      153,   78,   77,  154,   77,   77,   78,   77,   78,   78,

       77,   78,  160,  157,   78,  159,  162,  158,   77,   77,
      161,  164,   78,   78,   77,   77,   77,   77,   78,   78,
       78,   78,  165,   77,   77,   77,  108,   78,   78,   78,
      167,  142,   77,  139,  139,  166,   78,  168,   77,  139,
       77,   77,   78,  169,   78,   78,   77,  171,  173,  138,
       78,   77,  170,  174,   77,   78,   77,  172,   78,   77,
       78,  137,  175,   78,   77,  176,   77,   77,   78,   77,
       78,   78,  108,   78,   77,   77,  181,  108,   78,   78,
      179,  180,   77,   77,   77,   77,   78,   78,   78,   78,
      182,  183,  184,  106,   77,   77,   77,  186,   78,   78,

       78,   77,   77,   77,  185,   78,   78,   78,   77,   77,
      187,   77,   78,   78,   77,   78,   77,  190,   78,   77,
       78,  191,   77,   78,  105,  192,   78,   77,  195,   77,
       77,   78,   54,   78,   78,  196,  200,  200,  104,  201,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  202,  202,  200,  200,  200,  200,
      202,  200,  200,  200,  200,  200,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  200,  200,  200,  200,
      100,   75,   74,   73,   62,   58,   57,   54,   52,  208,

      208,  208,  208,  208,  200,  200,  208,  208,  208,  208,
      200,  208,  208,  208,  208,  208,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,   47,   47,   47,   47,
       47,   47,   47,   47,   53,  208,   53,   53,   53,   53,
       53,   53,   59,  208,   59,   59,   59,   59,   59,   59,
       76,   76,   76,  101,  208,  101,  208,  101,  101,  101,
      101,  107,  208,  107,  107,  107,  107,  107,  107,  109,
      109,  109,  109,  109,  109,  109,  109,  113,  208,  113,
      113,  113,  113,  113,  113,  140,  208,  140,  140,  140,

      140,  140,  140,  141,  208,  141,  141,  141,  141,  141,
      141,  197,  208,  208,  197,  208,  197,  205,  205,    5,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208
    } ;

static yyconst short int yy_chk[674] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    3,    4,    7,   11,    7,   14,   20,
       21,   11,   18,    3,    4,   21,   20,   49,    3,    4,
       21,   18,   49,  220,   22,   14,   22,   22,   27,   31,
       34,   32,   27,   31,   34,   32,   32,   33,   70,   70,
       35,   33,   22,   32,   35,   34,   33,   31,   32,   36,

       72,   72,   37,   36,   33,   35,   37,   35,  206,   38,
       39,   40,   37,   38,   39,   40,   36,   41,   37,   39,
       51,   41,   51,   40,   40,   42,   38,  205,   43,   42,
      204,   40,   43,   41,   40,   71,  203,   71,   71,  201,
       43,   76,   42,   61,   78,   76,   61,   79,   78,  193,
       61,   79,  189,   71,   80,  102,   79,   81,   80,   61,
      102,   81,   81,  188,   82,   83,   84,   61,   82,   83,
       84,   61,   61,   80,   85,   83,   61,   86,   85,   87,
       82,   86,   61,   87,   61,   88,   61,   84,   61,   88,
      194,   89,   90,   85,   86,   89,   90,   87,   91,   92,

       93,  178,   91,   92,   93,   88,   95,   94,  194,   96,
       95,   94,   90,   96,   91,  177,   97,   93,   94,   92,
       97,   98,   96,   99,   95,   98,  119,   99,  114,  114,
      119,   94,  115,  115,   98,   97,   99,  116,  163,  117,
      198,  116,  116,  117,  114,  118,  119,  120,  117,  118,
      121,  120,  120,  122,  121,  123,  121,  122,  198,  123,
      123,  124,  122,  118,  125,  124,  126,  127,  125,  128,
      126,  127,  130,  128,  162,  129,  130,  141,  127,  129,
      131,  125,  132,  140,  131,  138,  132,  133,  130,  131,
      128,  133,  134,  129,  135,  136,  134,  143,  135,  136,

      144,  143,  135,  132,  144,  134,  137,  133,  145,  146,
      136,  143,  145,  146,  147,  148,  149,  150,  147,  148,
      149,  150,  146,  151,  152,  153,  112,  151,  152,  153,
      148,  111,  154,  110,  109,  147,  154,  150,  155,  107,
      156,  157,  155,  153,  156,  157,  158,  155,  157,  106,
      158,  159,  154,  158,  160,  159,  161,  156,  160,  164,
      161,  105,  159,  164,  165,  161,  166,  167,  165,  168,
      166,  167,   60,  168,  169,  170,  167,   59,  169,  170,
      165,  166,  172,  171,  173,  174,  172,  171,  173,  174,
      169,  171,  172,   56,  175,  176,  179,  174,  175,  176,

      179,  180,  181,  182,  173,  180,  181,  182,  183,  184,
      175,  185,  183,  184,  186,  185,  187,  179,  186,  190,
      187,  180,  191,  190,   55,  187,  191,  192,  190,  195,
      196,  192,   53,  195,  196,  192,  197,  197,   50,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  197,
      197,  197,  197,  197,  197,  197,  197,  197,  197,  200,
       45,   26,   25,   24,   17,   13,   12,   10,    9,    5,

        0,    0,    0,    0,  200,  200,    0,    0,    0,    0,
      200,    0,    0,    0,    0,    0,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  200,  200,  200,  200,
      200,  200,  200,  200,  200,  200,  209,  209,  209,  209,
      209,  209,  209,  209,  210,    0,  210,  210,  210,  210,
      210,  210,  211,    0,  211,  211,  211,  211,  211,  211,
      212,  212,  212,  213,    0,  213,    0,  213,  213,  213,
      213,  214,    0,  214,  214,  214,  214,  214,  214,  215,
      215,  215,  215,  215,  215,  215,  215,  216,    0,  216,
      216,  216,  216,  216,  216,  217,    0,  217,  217,  217,

      217,  217,  217,  218,    0,  218,  218,  218,  218,  218,
      218,  219,    0,    0,  219,    0,  219,  221,  221,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  208,  208,  208,
      208,  208,  208
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "q.l"
#define INITIAL 0
#line 2 "q.l"
	#include <stdio.h>
	#include <string.h>
	#include "q.tab.h"
      int yylineno;
	struct ConstantTable{
		char constant_name[100];
		char constant_type[100];
		int exist;
	}CT[1000];
	
	struct SymbolTable{
		char symbol_name[100];
		char symbol_type[100];
        char array_dimensions[100];
		char class[100];
        char value[100];
        char parameters[100];
        int line_number;
		int exist;
	}ST[1000];

	unsigned long hash(unsigned char *str)
	{
		unsigned long hash = 5381;
		int c;

		while (c = *str++)
			hash = ((hash << 5) + hash) + c;

		return hash;
	}

	int search_ConstantTable(char* str){
		unsigned long temp_val = hash(str);
		int val = temp_val%1000;
		
		if(CT[val].exist == 0){
			return 0;
		}
		
		else if(strcmp(CT[val].constant_name, str) == 0)
		{
			return 1;
		}
		else
		{
			for(int i = val+1 ; i!=val ; i = (i+1)%1000)
			{
				if(strcmp(CT[i].constant_name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}

	
	int search_SymbolTable(char* str){
		unsigned long temp_val = hash(str);
		int val = temp_val%1000;
		
		if(ST[val].exist == 0){
			return 0;
		}
		
		else if(strcmp(ST[val].symbol_name, str) == 0)
		{
			return 1;
		}
		else
		{
			for(int i = val+1 ; i!=val ; i = (i+1)%1000)
			{
				if(strcmp(ST[i].symbol_name,str)==0)
				{
					return 1;
				}
			}
			return 0;
		}
	}
	
	
	void insert_ConstantTable(char* name, char* type){
		int index = 0;
		 if(search_ConstantTable(name)){
			return;
		}
		else{
			unsigned long temp_val = hash(name);
			int val = temp_val%1000;
			if(CT[val].exist == 0){
				strcpy(CT[val].constant_name, name);
				strcpy(CT[val].constant_type, type);
				CT[val].exist = 1;
				return;
			}
			
			for(int i = val+1; i != val; i = (i+1)%1000){
				if(CT[i].exist == 0){
					index = i;
					break;
				}
			}
			strcpy(CT[index].constant_name, name);
			strcpy(CT[index].constant_type, type);
			CT[index].exist = 1;			
		}
	}
	
	void insert_SymbolTable(char* name, char* class){
		int index = 0;
		//printf("BBBB");
		 if(search_SymbolTable(name)){
			//printf("AAAAAA");
			return;
		}
		else{
			unsigned long temp_val = hash(name);
			int val = temp_val%1000;
			if(ST[val].exist == 0){
				strcpy(ST[val].symbol_name, name);
				strcpy(ST[val].class, class);
                ST[val].line_number = yylineno;
				ST[val].exist = 1;
				return;
			}
			
			for(int i = val+1; i != val; i = (i+1)%1000){
				if(ST[i].exist == 0){
					index = i;
					break;
				}
			}
			strcpy(ST[index].symbol_name, name);
			strcpy(ST[val].class, class);
			ST[index].exist = 1;			
		}
	}

	void insert_SymbolTable_type(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcpy(ST[i].symbol_type,str2);
			}
		}
    }

	void insert_SymbolTable_value(char *str1, char *str2)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcpy(ST[i].value,str2);
			}
		}
	}

    void insert_SymbolTable_arraydim(char *str1, char *dim)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcpy(ST[i].array_dimensions,dim);
			}
		}
	}

    void insert_SymbolTable_funcparam(char *str1, char *param)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				strcat(ST[i].parameters," ");
                strcat(ST[i].parameters,param);
			}
		}
	}

	void insert_SymbolTable_line(char *str1, int line)
	{
		for(int i = 0 ; i < 1000 ; i++)
		{
			if(strcmp(ST[i].symbol_name,str1)==0)
			{
				ST[i].line_number = line;
			}
		}
	}

	void printConstantTable(){
		printf("%20s   %20s\n", "CONSTANT","TYPE");
		for(int i = 0; i < 1000; ++i){
			if(CT[i].exist == 0)
				continue;
				
			printf("%20s   %20s\n", CT[i].constant_name, CT[i].constant_type);
		}
	}

	void printSymbolTable(){
        printf("%10s   %18s   %10s   %10s   %10s   %10s   %10s\n","SYMBOL", "CLASS", "TYPE","VALUE","DIMENSIONS","PARAMETERS","LINE NO");
		for(int i = 0; i < 1000; ++i){
			if(ST[i].exist == 0)
				continue;
			printf("%10s   %18s   %10s   %10s   %10s   %10s   %d\n", ST[i].symbol_name, ST[i].class, ST[i].symbol_type, ST[i].value,ST[i].array_dimensions,ST[i].parameters, ST[i].line_number);
		}
	}
	char current_identifier[20];
	char current_type[20];
	char current_value[20];
    char current_function[20];
	char previous_operator[20];
	int flag;

#define MLCOMMENT 1

#line 809 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 235 "q.l"


	int nested_count = 0;
	int check_nested = 0;

#line 966 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 209 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 620 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 240 "q.l"
{yylineno++;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 241 "q.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 242 "q.l"
{ } 
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 243 "q.l"
{ }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 245 "q.l"
{ BEGIN MLCOMMENT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 246 "q.l"
{ ++nested_count; 
												check_nested = 1;
											 }	
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 249 "q.l"
{ if (nested_count) --nested_count;
											   else{ if(check_nested){
														check_nested = 0;
														BEGIN INITIAL;
														}
													 else{
														BEGIN INITIAL;
													}
											    } 
											 }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 259 "q.l"
; 
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 260 "q.l"
;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 261 "q.l"
;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 262 "q.l"
;
	YY_BREAK
case YY_STATE_EOF(MLCOMMENT):
#line 263 "q.l"
{ printf("Line No. %d ERROR: MULTI LINE COMMENT NOT CLOSED\n", yylineno); return 0;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 265 "q.l"
{return *yytext;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 266 "q.l"
{return *yytext;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 267 "q.l"
{return *yytext;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 268 "q.l"
{return *yytext;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 269 "q.l"
{return *yytext;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 270 "q.l"
{return *yytext;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 271 "q.l"
{return *yytext;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 272 "q.l"
{return *yytext;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 276 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword"); return CHAR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 277 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword"); return DOUBLE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 278 "q.l"
{ insert_SymbolTable_line(yytext, yylineno); insert_SymbolTable(yytext, "Keyword"); return ELSE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 279 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");return FLOAT;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 280 "q.l"
{ insert_SymbolTable(yytext, "Keyword"); return WHILE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 281 "q.l"
{ insert_SymbolTable(yytext, "Keyword"); return DO;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 282 "q.l"
{ insert_SymbolTable(yytext, "Keyword"); return FOR;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 283 "q.l"
{ insert_SymbolTable(yytext, "Keyword"); return IF;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 284 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");return INT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 285 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return LONG;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 286 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return RETURN;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 287 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return SHORT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 288 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return SIGNED;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 289 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return SIZEOF;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 290 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return STRUCT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 291 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return UNSIGNED;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 292 "q.l"
{ strcpy(current_type,yytext); insert_SymbolTable(yytext, "Keyword");  return VOID;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 293 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return BREAK;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 294 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return CONTINUE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 295 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return GOTO;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 296 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return SWITCH;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 297 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return CASE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 298 "q.l"
{ insert_SymbolTable(yytext, "Keyword");  return DEFAULT;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 300 "q.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext,"String Constant"); return string_constant;}        
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 301 "q.l"
{ printf("Line No. %d ERROR: UNCLOSED STRING - %s\n", yylineno, yytext); return 0;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 302 "q.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext,"Character Constant"); return character_constant;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 303 "q.l"
{printf("Line No. %d ERROR: NOT A CHARACTER - %s\n", yylineno, yytext); return 0; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 304 "q.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext, "Floating Constant"); return float_constant;} 
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 305 "q.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext, "Floating Constant"); return float_constant;}                                             
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 306 "q.l"
{strcpy(current_value,yytext); insert_ConstantTable(yytext, "Number Constant"); return integer_constant;}    
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 307 "q.l"
{strcpy(current_identifier,yytext);insert_SymbolTable(yytext,"Identifier");  return identifier;}
	YY_BREAK
case 51:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 308 "q.l"
{strcpy(current_identifier,yytext);insert_SymbolTable(yytext,"Array Identifier");  return identifier;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 309 "q.l"
;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 311 "q.l"
{return *yytext;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 312 "q.l"
{return *yytext;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 313 "q.l"
{return *yytext;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 314 "q.l"
{return *yytext;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 315 "q.l"
{return *yytext;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 316 "q.l"
{return *yytext;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 317 "q.l"
{return *yytext; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 318 "q.l"
{return *yytext; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 319 "q.l"
{return INCREMENT;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 320 "q.l"
{return DECREMENT;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 321 "q.l"
{return NOT;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 322 "q.l"
{return ADD_EQUAL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 323 "q.l"
{return SUBTRACT_EQUAL;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 324 "q.l"
{return MULTIPLY_EQUAL;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 325 "q.l"
{return DIVIDE_EQUAL;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 326 "q.l"
{return MOD_EQUAL;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 327 "q.l"
{return AND_AND;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 331 "q.l"
{return OR_OR;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 332 "q.l"
{return GREAT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 333 "q.l"
{return LESS;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 334 "q.l"
{return GREAT_EQUAL;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 335 "q.l"
{return LESS_EQUAL;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 336 "q.l"
{return EQUAL;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 337 "q.l"
{return NOT_EQUAL;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 338 "q.l"
{ flag = 1;
											   if(yytext[0] == '#')
													printf("Line No. %d PREPROCESSOR ERROR - %s\n", yylineno, yytext);
											   else
													printf("Line No. %d ERROR ILLEGAL CHARACTER - %s\n", yylineno, yytext);
											  return 0;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 345 "q.l"
ECHO;
	YY_BREAK
#line 1462 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 209 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 209 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 208);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 345 "q.l"
